# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    gradle(task: 'clean')
    gradle(
      task: 'assemble',
      build_type: 'Release'
    )
    crashlytics

    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  desc "Deploy a new version to the Google Play Store"
  lane :deploy do
    gradle(task: 'clean')
    gradle(
      task: 'assemble',
      build_type: 'Release'
    )
    upload_to_play_store(
      track: 'internal',
      apk: lane_context[SharedValues::GRADLE_APK_OUTPUT_PATH]
    )
  end

  desc "Build release APK"
  lane :build_release do
    gradle(task: 'clean')
    gradle(
      task: 'assemble',
      build_type: 'Release'
    )
  end

  desc "Build and deploy to internal testing"
  lane :internal do
    build_release
    upload_to_play_store(
      track: 'internal',
      apk: lane_context[SharedValues::GRADLE_APK_OUTPUT_PATH],
      skip_upload_metadata: true,
      skip_upload_images: true,
      skip_upload_screenshots: true
    )
  end

  desc "Build and deploy to beta testing"
  lane :beta_deploy do
    build_release
    upload_to_play_store(
      track: 'beta',
      apk: lane_context[SharedValues::GRADLE_APK_OUTPUT_PATH]
    )
  end

  desc "Build and deploy to production"
  lane :production do
    build_release
    upload_to_play_store(
      track: 'production',
      apk: lane_context[SharedValues::GRADLE_APK_OUTPUT_PATH]
    )
  end
end